server.port=8080
mqtt.username=admin
mqtt.password=admin
mqtt.host=tcp://localhost:1883
mqtt.sender.clientId=mqttProducer
mqtt.sender.defaultTopic=topic
mqtt.receiver.clientId=1024
mqtt.receiver.defaultTopic=topic,normal
