server.port=56081
swagger.enable=true
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url=jdbc:mysql://192.168.1.200:3308/bank1?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&useSSL=false
spring.datasource.username=root
spring.datasource.password=wZKicHYoEgIMIVAU
rocketmq.producer.group=producer_bank1
rocketmq.name-server=127.0.0.1:9876
logging.level.root=info
logging.level.org.springframework.web=info
logging.level.cc.ivera.wanxintx.ensuredemo=debug

