package cc.ivera.ragdemo.service.ragops;

/**
 * Abstraction for object storage backends (local filesystem, MinIO, S3, etc.).
 * <p>
 * All object keys are tenant-scoped strings generated by {@code TenantScopedObjectKeyFactory}.
 * Implementations must be thread-safe and idempotent for save/delete operations.
 */
public interface ObjectStorageService {

    /**
     * Save an object using a hash-based key (legacy, non-tenant-scoped).
     */
    StoredObject save(String fileHash, String fileName, byte[] bytes);

    /**
     * Save an original document file with tenant-scoped key.
     */
    StoredObject saveOriginal(Long tenantId,
                              Long knowledgeBaseId,
                              String documentRef,
                              String fileHash,
                              String fileName,
                              byte[] bytes);

    /**
     * Save a document version file with tenant-scoped key.
     */
    StoredObject saveVersion(Long tenantId,
                             Long knowledgeBaseId,
                             String documentRef,
                             Integer versionNo,
                             String fileHash,
                             String fileName,
                             byte[] bytes);

    /**
     * Read object content by key.
     *
     * @param objectKey the object key returned by save/saveOriginal/saveVersion
     * @return the raw bytes
     * @throws IllegalStateException if the object cannot be read
     */
    byte[] read(String objectKey);

    /**
     * Delete a single object if it exists.
     *
     * @return true if the object was deleted, false if it did not exist
     */
    boolean deleteIfExists(String objectKey);

    /**
     * Count objects belonging to a tenant.
     */
    long countTenantObjects(String environment, Long tenantId);

    /**
     * Delete all objects belonging to a tenant.
     *
     * @return the number of deleted objects
     */
    long deleteTenantObjects(String environment, Long tenantId);
}
