server:
  port: 18083
spring:
  application:
    name: elasticjob-order-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:192.168.220.200}:${MYSQL_PORT:3306}/order_demo?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root123456}
elasticjob:
  reg-center:
    server-lists: ${ZOOKEEPER_SERVER:192.168.220.200:2181}
    namespace: order-timeout-job
order:
  job:
    batch-size: 100
