server:
  port: 8080 #服务端口

spring:
  application:
    name: payment-demo #应用的名字

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  rabbitmq:
    host: 192.168.220.200
    port: 5672
    username: guest
    password: guest

  datasource:
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.220.200:3308/payment_demo?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: cpc!23#@

mybatis-plus:
  configuration: #sql日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:cc/ivera/mapper/xml/*.xml

logging:
  level:
    root: info


payment:
  order:
    close-delay-ms: 60000
