CREATE DATABASE IF NOT EXISTS test DEFAULT CHARACTER SET utf8mb4;
USE test;

DROP TABLE IF EXISTS user_profile;

CREATE TABLE user_profile (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    name VARCHAR(64) NOT NULL COMMENT '姓名',
    hobbies JSON DEFAULT NULL COMMENT '爱好，List<String>',
    tags JSON DEFAULT NULL COMMENT '标签，List<TagItem>',
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
