CREATE TABLE IF NOT EXISTS file_resource (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    file_name VARCHAR(255) NOT NULL,
    file_md5 VARCHAR(64) NOT NULL,
    file_size BIGINT NULL,
    content_type VARCHAR(128) NULL,
    bucket VARCHAR(128) NOT NULL,
    object_name VARCHAR(512) NOT NULL,
    file_url VARCHAR(512) NOT NULL,
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_md5 (file_md5)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
