spring:
  data:
    redis:
      host: 192.168.1.200
      port: 6379
      database: 0
      password: cpc!23#@

redisson:
  config: |
    singleServerConfig:
      address: "redis://192.168.1.200:6379"
      password: "cpc!23#
      database: 0