CREATE TABLE IF NOT EXISTS chat_memory (
memory_id VARCHAR(64) NOT NULL PRIMARY KEY,
messages_json LONGTEXT NOT NULL,
updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);