mqtt.broker.serverUri=tcp://localhost:1883
mqtt.broker.username=admin
mqtt.broker.password=admin
mqtt.clientId=mqtt-customer
#指定要订阅的topic
mqtt.topic=topic
mqtt.qos=2
mqtt.completionTimeout=5000
server.port=8090