CREATE DATABASE IF NOT EXISTS order_demo DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS xxl_job DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS powerjob DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE order_demo;
CREATE TABLE IF NOT EXISTS t_order (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  order_no VARCHAR(64) NOT NULL UNIQUE,
  user_id BIGINT NOT NULL,
  amount DECIMAL(18,2) NOT NULL,
  status VARCHAR(32) NOT NULL COMMENT 'UNPAID/PAID/CLOSED',
  pay_deadline DATETIME NOT NULL,
  close_reason VARCHAR(255),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  version INT NOT NULL DEFAULT 0,
  KEY idx_status_deadline (status, pay_deadline)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS job_cron_config (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  job_type VARCHAR(32) NOT NULL UNIQUE COMMENT 'XXL/POWER/ELASTIC',
  job_name VARCHAR(128) NOT NULL,
  cron_expr VARCHAR(64) NOT NULL,
  enabled TINYINT NOT NULL DEFAULT 1,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS order_close_job_log (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  job_type VARCHAR(32) NOT NULL,
  instance_id VARCHAR(128),
  batch_no VARCHAR(64) NOT NULL,
  scanned_count INT NOT NULL DEFAULT 0,
  closed_count INT NOT NULL DEFAULT 0,
  status VARCHAR(32) NOT NULL,
  error_msg TEXT,
  started_at DATETIME NOT NULL,
  finished_at DATETIME
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT INTO job_cron_config(job_type, job_name, cron_expr, enabled) VALUES
('XXL','xxlCloseTimeoutUnpaidOrder','0 */1 * * * ?',1),
('POWER','powerCloseTimeoutUnpaidOrder','0 */1 * * * ?',1),
('ELASTIC','elasticCloseTimeoutUnpaidOrder','0 */1 * * * ?',1)
ON DUPLICATE KEY UPDATE cron_expr=VALUES(cron_expr), enabled=VALUES(enabled);
INSERT INTO t_order(order_no,user_id,amount,status,pay_deadline) VALUES
('NO_TIMEOUT_001',1001,99.00,'UNPAID',DATE_SUB(NOW(), INTERVAL 10 MINUTE)),
('NO_TIMEOUT_002',1002,199.00,'UNPAID',DATE_SUB(NOW(), INTERVAL 20 MINUTE)),
('NO_NORMAL_001',1003,299.00,'UNPAID',DATE_ADD(NOW(), INTERVAL 20 MINUTE)),
('NO_PAID_001',1004,399.00,'PAID',DATE_SUB(NOW(), INTERVAL 30 MINUTE))
ON DUPLICATE KEY UPDATE order_no=order_no;
