version: "3.5"

services:
  etcd:
    container_name: milvus-etcd
    image: rancher/etcd:v3.4.3
    command: >
      etcd
      -advertise-client-urls=http://0.0.0.0:2379
      -listen-client-urls=http://0.0.0.0:2379
      -listen-peer-urls=http://0.0.0.0:2380
      -initial-advertise-peer-urls=http://0.0.0.0:2380
      -initial-cluster=default=http://0.0.0.0:2380
      -initial-cluster-token=milvus-etcd
      -initial-cluster-state=new
    ports:
      - "2379:2379"
      - "2380:2380"

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-01-02T09-40-09Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: minio server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"

  milvus:
    container_name: milvus
    image: milvusdb/milvus:v2.3.7
    command: [ "milvus", "run", "standalone" ]
    environment:
      ETCD_ENDPOINTS: "etcd:2379"
      MINIO_ADDRESS: "minio:9000"
    depends_on:
      - etcd
      - minio
    ports:
      - "19530:19530"
      - "9091:9091"

  attu:
    container_name: milvus-attu
    image: zilliz/attu:v2.6
    environment:
      - MILVUS_URL=milvus-standalone:19530
    ports:
      - "8000:3000"
    depends_on:
      - milvus