powerjob:
  worker:
    enabled: true
    app-name: order-service
    password: "123456"
    server-address: 192.168.220.200:7700
    protocol: http
    port: 27777
    allow-lazy-connect-server: false
