# cluster 名称
brokerClusterName = DefaultCluster
# broker 名称
brokerName = broker-a
# 0 表示 Master，>0 表示 Slave
brokerId = 0
# 每天几点删除日志
deleteWhen = 04
# 日志保留时间（小时）
fileReservedTime = 48
# 角色：ASYNC_MASTER (异步刷盘), SYNC_MASTER (同步刷盘), SLAVE
brokerRole = ASYNC_MASTER
# 刷盘方式：ASYNC_FLUSH (异步), SYNC_FLUSH (同步)
flushDiskType = ASYNC_FLUSH

# 自动创建 Topic (生产环境建议关闭)
autoCreateTopicEnable = true

# --- 关键配置 ---
# 宿主机 IP，如果不设置，外网/宿主机可能无法连接
# 如果你是本地开发，写 127.0.0.1 即可；如果是服务器，写服务器外网 IP
brokerIP1 = 192.168.1.200