CREATE DATABASE IF NOT EXISTS points_demo CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE points_demo;

CREATE TABLE IF NOT EXISTS user_info (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(64) NOT NULL,
    mobile VARCHAR(32),
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_points (
    user_id BIGINT PRIMARY KEY,
    points INT NOT NULL DEFAULT 0,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS points_log (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    business_id VARCHAR(64) NOT NULL,
    points INT NOT NULL,
    status TINYINT NOT NULL DEFAULT 0,
    retry_count INT NOT NULL DEFAULT 0,
    err_msg VARCHAR(255),
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_business (business_id)
);

CREATE TABLE IF NOT EXISTS points_manual_process (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    business_id VARCHAR(64) NOT NULL,
    points INT NOT NULL,
    status TINYINT NOT NULL DEFAULT 0,
    last_err_msg VARCHAR(255),
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP
);
